import { ContentItem, GenerationRun, ScheduleItem, BrandSettings, DashboardStats, ScrapedItem } from './types';

export const mockStats: DashboardStats = {
  totalContent: 47,
  published: 23,
  scheduled: 8,
  drafts: 16,
  generatedThisWeek: 12,
  publishRate: 78,
};

export const mockContent: ContentItem[] = [
  {
    id: '1',
    title: 'The Future of AI-Powered Content Creation in 2026',
    body: `# The Future of AI-Powered Content Creation in 2026\n\nArtificial intelligence has transformed the landscape of content creation...\n\n## Key Trends\n\n### 1. Autonomous Content Agents\nDeep agents are revolutionizing how teams produce content at scale...\n\n### 2. Brand-Aware Generation\nModern AI systems understand brand voice deeply...\n\n### 3. Multi-Format Workflows\nA single topic can spawn blog posts, social media content, and newsletters simultaneously...\n\n## What This Means for Teams\n\nContent teams are shifting from production to curation and strategy...`,
    contentType: 'blog',
    status: 'published',
    createdAt: '2026-03-25T10:00:00Z',
    updatedAt: '2026-03-26T14:30:00Z',
    publishedAt: '2026-03-27T09:00:00Z',
    topic: 'AI Content Creation',
    wordCount: 1842,
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
    tags: ['AI', 'Content Strategy', 'Technology'],
    researchNotes: [
      {
        id: 'r1',
        topic: 'AI Content Creation Trends 2026',
        findings: 'Major shift toward autonomous agents. 73% of enterprise teams using AI for first drafts. Quality gap narrowing with brand-aware models.',
        sources: ['Gartner Report 2026', 'Content Marketing Institute Survey'],
        createdAt: '2026-03-25T10:05:00Z',
      },
    ],
  },
  {
    id: '2',
    title: 'Why Deep Agents Are the Next Evolution',
    body: 'Deep agents represent a fundamental shift in how we think about AI assistance...',
    contentType: 'linkedin',
    status: 'review',
    createdAt: '2026-03-28T08:00:00Z',
    updatedAt: '2026-03-28T12:00:00Z',
    topic: 'Deep Agents',
    wordCount: 320,
    tags: ['AI', 'Deep Agents', 'LinkedIn'],
  },
  {
    id: '3',
    title: '5 Ways to Leverage LangGraph for Content Workflows',
    body: 'LangGraph provides the graph-based orchestration layer...',
    contentType: 'blog',
    status: 'draft',
    createdAt: '2026-03-29T14:00:00Z',
    updatedAt: '2026-03-29T14:00:00Z',
    topic: 'LangGraph Workflows',
    wordCount: 2100,
    tags: ['LangGraph', 'Automation', 'Tutorial'],
  },
  {
    id: '4',
    title: 'Content Automation Thread 🧵',
    body: '1/ Content automation is not about replacing writers...\n\n2/ It\'s about augmenting creative capacity...',
    contentType: 'twitter',
    status: 'approved',
    createdAt: '2026-03-30T09:00:00Z',
    updatedAt: '2026-03-30T11:00:00Z',
    topic: 'Content Automation',
    wordCount: 180,
    tags: ['Automation', 'Twitter Thread'],
  },
  {
    id: '5',
    title: 'Weekly AI Insights Newsletter — Issue #14',
    body: 'This week in AI: autonomous content agents, new publishing integrations...',
    contentType: 'newsletter',
    status: 'scheduled',
    createdAt: '2026-03-29T16:00:00Z',
    updatedAt: '2026-03-30T10:00:00Z',
    scheduledFor: '2026-04-01T08:00:00Z',
    topic: 'AI Weekly Roundup',
    wordCount: 950,
    tags: ['Newsletter', 'AI', 'Weekly'],
  },
  {
    id: '6',
    title: 'Building a Content Pipeline with FastAPI',
    body: 'Learn how to set up a production-grade content pipeline...',
    contentType: 'blog',
    status: 'draft',
    createdAt: '2026-03-30T15:00:00Z',
    updatedAt: '2026-03-30T15:00:00Z',
    topic: 'FastAPI Content Pipeline',
    wordCount: 0,
    tags: ['FastAPI', 'Python', 'Tutorial'],
  },
];

export const mockSchedule: ScheduleItem[] = [
  { id: 's1', contentId: '5', contentTitle: 'Weekly AI Insights Newsletter — Issue #14', contentType: 'newsletter', publishAt: '2026-04-01T08:00:00Z', platform: 'Email', status: 'scheduled' },
  { id: 's2', contentId: '4', contentTitle: 'Content Automation Thread 🧵', contentType: 'twitter', publishAt: '2026-04-02T12:00:00Z', platform: 'Twitter/X', status: 'approved' },
  { id: 's3', contentId: '2', contentTitle: 'Why Deep Agents Are the Next Evolution', contentType: 'linkedin', publishAt: '2026-04-03T09:00:00Z', platform: 'LinkedIn', status: 'review' },
  { id: 's4', contentId: '1', contentTitle: 'The Future of AI-Powered Content Creation in 2026', contentType: 'blog', publishAt: '2026-03-27T09:00:00Z', platform: 'WordPress', status: 'published' },
];

export const mockBrandSettings: BrandSettings = {
  tone: 'Professional yet approachable. Knowledgeable without being condescending. Forward-thinking and optimistic about technology.',
  audience: 'Technical content marketers, developer advocates, and startup founders aged 28-45 who are exploring AI augmentation for their content workflows.',
  styleGuidelines: 'Use active voice. Keep paragraphs short (3-4 sentences). Include concrete examples. Avoid jargon without explanation. Use data points when available.',
  blogTemplate: '# [Title]\n\n[Hook — 1-2 sentences that create curiosity]\n\n## The Problem\n[Context setting]\n\n## Key Insights\n### 1. [Insight]\n### 2. [Insight]\n### 3. [Insight]\n\n## What This Means\n[Practical takeaways]\n\n## Next Steps\n[CTA]',
  linkedinTemplate: '[Hook line — question or bold statement]\n\n[3-4 short paragraphs with insights]\n\n[Takeaway or question for engagement]\n\n#relevant #hashtags',
  twitterTemplate: '1/ [Hook]\n\n2/ [Context]\n\n3-7/ [Key points]\n\n8/ [CTA or summary]',
  companyName: 'ContentForge',
  industry: 'AI-Powered Content Technology',
};

export const mockStreamSteps = [
  { type: 'planning' as const, message: 'Planning content structure...', delay: 800 },
  { type: 'planning' as const, message: 'Created 4 todo items for this generation', delay: 1200 },
  { type: 'researching' as const, message: 'Research sub-agent activated — searching for recent data...', delay: 1500 },
  { type: 'researching' as const, message: 'Found 6 relevant sources on the topic', delay: 2500 },
  { type: 'researching' as const, message: 'Analyzing source credibility and extracting key findings...', delay: 1800 },
  { type: 'writing' as const, message: 'Drafting introduction with hook...', delay: 2000 },
  { type: 'writing' as const, message: 'Writing main body sections...', delay: 3000 },
  { type: 'writing' as const, message: 'Adding data points and examples from research...', delay: 2000 },
  { type: 'writing' as const, message: 'Crafting conclusion and CTA...', delay: 1500 },
  { type: 'generating_image' as const, message: 'Generating hero image with DALL-E...', delay: 3000 },
  { type: 'reviewing' as const, message: 'Editor sub-agent reviewing against brand guidelines...', delay: 2000 },
  { type: 'reviewing' as const, message: 'Minor tone adjustments applied', delay: 1000 },
  { type: 'completed' as const, message: 'Content generation complete!', delay: 500 },
];
